baseurl = "https://mediathekview.de"
title = "MediathekView"
languageCode = "de-de"
DefaultContentLanguage = "de"
theme = "mediathekview"

enableRobotsTXT = true

[permalinks]
    post = "/:year/:month/:day/:slug/"
    code = "/:slug/"

[taxonomies]
    tag = "tags"

[author]
    name = "Mediathekview"
    email = "support@mediathekview.de"

[params]
    topline = "Die offizelle MediathekView Homepage"
    footline = "Homepage Version: 1.13.7"

    copyright = "(c) 2016-2020 Copyright by MediathekView Team"
    title = "MediathekView" # Site title

    # Show a sidebar menu
    showrightsidebar = true

    # Sidebar social links.
    github = "mediathekview"


    [[menu.main]]
    name = "Neuigkeiten"
    title = "Neuigkeiten"
    pre = ""
    weight = 1
    identifier = "neuigkeiten"

    [[menu.main]]
    name = "Neuigkeiten"
    title = "Neuigkeiten"
    pre = ""
    weight = 1
    parent = "neuigkeiten"
    url = "/news"

    [[menu.main]]
    name = "Changelogs"
    title = "Changelogs"
    pre = ""
    weight = 2
    parent = "neuigkeiten"
    url = "/changelog"

    [[menu.main]]
    name = "Hilfe"
    title = "Hilfe"
    pre =""
    weight = 4
    identifier = "hilfe"

    [[menu.main]]
    name = "Screenshots"
    title = "Screenshots"
    pre = ""
    weight = 3
    parent = "hilfe"
    url = "/screenshots"

    [[menu.main]]
    name = "Forum"
    title = "Forum"
    parent = "hilfe"
    weight = 4
    url = "https://forum.mediathekview.de"

    [[menu.main]]
    name = "Unterstützen"
    title = "Unterstützen"
    weight = 5
    identifier = "unterstuetzen"

    [[menu.main]]
    name = "Github"
    title = "Github"
    url = "https://github.com/mediathekview/mediathekview"
    parent = "unterstuetzen"

    [[menu.main]]
    name = "Web Client"
    title = "Web Client"
    weight = 16
    url = "https://mediathekviewweb.de"

    [[menu.footer]]
    name = "Impressum"
    pre = "<i>-</i>"
    weight = 1
    url = "/impressum/"

    [[menu.footer]]
    name = "Über uns"
    pre = "-"
    weight = 2
    url = "/ueberuns/"

    [[menu.footer]]
    name = "Lizenz"
    weight = 3
    url = "/lizenz/"

[blackfriday]
    hrefTargetBlank = true
    latexDashes = true
    plainIdAnchors = true
